# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source "https://github.com/CocoaPods/Old-Specs"

pod 'HMSegmentedControl'
pod 'ChameleonFramework', '~> 2.1'
pod 'pop', '~> 1.0'